services:
  pypdf-extractor:
    image: openwebui-loaders
    build: .
    container_name: openwebui-loaders
    networks:
    - shared-net
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      API_KEY: "secret"
      WORKERS: 4
      
networks:
  shared-net:
    external: true
